version: '3'
services:
  blog-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: blog-back-api
    stdin_open: true
    volumes:
      - ./:/app/back-api
    ports:
     - 8000:8080
    depends_on:
     - blog-db
  blog-db:
    image: mysql:8.0
    container_name: blog-db-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: pass